# Generated by Django 4.0.5 on 2022-06-09 15:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynasty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynasty', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmperorYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('dynasty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict_model.dynasty')),
            ],
        ),
        migrations.CreateModel(
            name='Porcelain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('image', models.ImageField(upload_to='porcelain')),
                ('introduce', models.TextField()),
                ('datetime', models.DateTimeField(default=datetime.datetime(2022, 6, 9, 15, 57, 43, 9049, tzinfo=utc))),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict_model.emperoryear')),
            ],
        ),
    ]
