# Generated by Django 4.0.5 on 2022-06-10 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import predict_model.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predict_model', '0002_alter_dynasty_dynasty_alter_emperoryear_dynasty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porcelain',
            name='image',
            field=models.ImageField(upload_to=predict_model.models.upload_porcelain_image),
        ),
        migrations.CreateModel(
            name='PrdictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=10)),
                ('value', models.FloatField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('predict_age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_age', to='predict_model.emperoryear')),
                ('truth_age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict_model.emperoryear')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
