# Generated by Django 4.0.5 on 2022-06-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict_model', '0003_alter_porcelain_image_prdictmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdictmodel',
            name='description',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prdictmodel',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prdictmodel',
            name='truth_age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predict_model.emperoryear'),
        ),
        migrations.AlterField(
            model_name='prdictmodel',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
