# Generated by Django 4.0.5 on 2022-06-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_model', '0004_alter_prdictmodel_description_alter_prdictmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdictmodel',
            name='hyper_spectral',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='prdictmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
