# Generated by Django 4.0.5 on 2022-06-09 17:11

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEvaluationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to=item.models.evaluation_directory_path, verbose_name='商品评价图片')),
            ],
            options={
                'verbose_name': '商品评价关联图',
                'verbose_name_plural': '商品评价关联图',
            },
        ),
    ]
